### ISSUE TITLE
Am I the only one this doesn't work for.  It fails when I try to deploy?

### ISSUE THREAD

**Issue by bpawnzZ** [codebam/cf-workers-telegram-bot#698]
When I press the deploy buttton. after i enter my cloudflare id and api it appears as it is going to work but then errors out.  and when I try to run with wrangler I also get an error.  below are screenshots.  Am i retarded or something.. Lol.. Thank you for your help.
![Screenshot_20240301_100850](https://github.com/codebam/cf-workers-telegram-bot/assets/151177455/b2a16562-598b-4f60-910c-0003fa9076cc)
![Screenshot_20240301_100548](https://github.com/codebam/cf-workers-telegram-bot/assets/151177455/c800c808-5bb7-4a52-b5c3-14f71cef893c)

PS.. each time I ran I removed the create db and worker and went through the build fresh.  But i still think it is something db related.  Would appreciate if someone could point me in the right direction.

**Comment by bpawnzZ** [comment]
figured out

**Comment by Muzych** [comment]
how did you solve it

**Comment by bpawnzZ** [comment]
> how did you solve it

Just saw this. I'm not home atm but I was something to do with linking the database correctly and having the right npm modules installed. When I get home this evening I will update and let you know.
