### ISSUE TITLE
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import

### ISSUE THREAD

**Issue by humanismusic** [codebam/cf-workers-telegram-bot#770]
Hi, 

Looks great but having trouble - when trying to test locally using Javascript I see this error: 

```Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'C:\Users\M\Documents\code\project\node_modules\@codebam\cf-workers-telegram-bot\dist\types' is not supported resolving ES modules imported from C:\Users\M\Documents\code\project\node_modules\@codebam\cf-workers-telegram-bot\dist\telegram_bot.js```.

importing like so:

`import TelegramBot, { TelegramExecutionContext } from '@codebam/cf-workers-telegram-bot';`

I'm using `"type": "module"` in package.json. 

Any idea what's going on?

**Comment by codebam** [comment]
Hey, not exactly sure what's going on there. I've created a new template repository you can use if you'd like that uses JavaScript. https://github.com/codebam/cwtb-consumer-js
